version: "3.4"

volumes:
  redis_volume:
    driver: local
  psql_volume:
    driver: local

services:
  psql:
    container_name: c-psql
    hostname: psql-host
    image: postgres:alpine
    restart: always
    healthcheck:
      test: pg_isready -U testuser
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=locationdb
    ports:
      - "5432:5432"
    volumes:
      - psql_volume:/data/psql

  location-api:
    depends_on:
      psql:
        condition: service_healthy
        restart: true
    container_name: c-api
    build:
      context: .
      target: production
    environment:
      - PSQL_PORT=5432
    ports:
      - 4001:4001
